- id: check-authenticode-signatures
  name: check for Authenticode signatures in PowerShell files
  description: prevent adding Authenticode signatures to commits
  entry: hooks/check_authenticode_signatures.ps1
  language: script
  types: [powershell]

- id: check-regex
  name: check for files matching regex
  description: prevent adding files matching regex to commits
  entry: hooks/check_regex.sh
  language: script
  types: [text]
