repos:
  - repo: https://github.com/0x4448/pre-commit-hooks
    rev: v0.0.3
    hooks:
      - id: check-authenticode-signatures
      - id: check-regex

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
