repos:
  - repo: https://github.com/0x4448/pre-commit-hooks
    rev: v0.0.3
    hooks:
      - id: check-authenticode-signatures
      - id: check-regex

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
