- id: check-authenticode-signature
  name: check for Authenticode signatures in PowerShell files
  description: prevent adding Authenticode signatures to commits
  entry: check-authenticode-signature
  language: python
  types: [powershell]

- id: check-regex
  name: check for files matching regex
  description: prevent adding files matching regex to commits
  entry: hooks/check_regex.sh
  language: script
  types: [text]

- id: dotnet-format
  name: dotnet format (.NET 6 SDK)
  description: check dotnet solution
  entry: dotnet-format
  language: python
  types: [c#]

- id: dotnet-format-whitespace
  name: dotnet format whitespace (.NET 6 SDK)
  description: check for whitespace formatting problems
  entry: dotnet-format-whitespace
  language: python
  types: [c#]
